ransac:
  minimum_points_for_consensus: 5
  maximum_iterations_per_fitting: 100
  maximum_fitted_models: 10
  consensus_error_threshold: 0.1
maximum_disagreement_ratio: 0
measurement_distance_variance_factor: 0.15
measurement_bearing_variance: 0.1
measurement_elevation_variance: 0.1

