output:
  file:
    enabled: true
    path: /home/robotx/DataStream
  network:
    enabled: false
    pub_port: 12000
    sub_port: 12001
    high_water_mark: 50
reaction_handles:
  reaction_statistics: false
  data_points: false
  game_controller: false
  behaviour: false
  sensors: true
  image: true
  classified_image: false
  goals: false
  balls: false
  localisation: false
  visual_horizon: false
  point_scan: false
