maxVelocity: 3
lineOfSightMeters: 20.0
testPathGoalTolerance: 2
tasks:
    taskPath0: #encoded as North, East
        -
          - [1, 1]
          - [1, 1]
          - [1, 1]
          - [1, 1]
        -
          - [1, 1]
          - [1, 1]
          - [1, 1]
          - [1, 1]
          - [1, 1]
    taskPath1: #encoded as North, East
        -
          - [1, 1]
          - [1, 1]
          - [1, 1]
          - [1, 1]
          - [1, 1]
          - [1, 1]
          - [1, 1]
          - [1, 1]
          - [1, 1]
